---
# https://taskfile.dev

version: '3'

tasks:
  backup:
    desc: Backup a LastPass vault
    cmds:
      - lpass export > {{ .FILENAME }}
    vars:
      FILENAME: backup.csv
  clean:
    desc: Clean the dir of csv files
    cmds:
      - rm *.csv
  lint:
    desc: Lint the project
    cmds:
      - shellcheck -x ./check-urls.sh
  pinentry:
    desc: Set pinentry
    cmds:
      - ./check-urls.sh {{ .FILENAME }}
    env:
      LPASS_DISABLE_PINENTRY: 1
    vars:
      FILENAME: dead-urls.csv
  run:
    desc: Run
    cmds:
      - ./check-urls.sh {{ .FILENAME }}
    vars:
      FILENAME: dead-urls.csv
  rm:
    desc: Remove LastPass items
    cmds:
      - ./rm-dead-url-items.sh {{ .FILENAME }}
    vars:
      FILENAME: dead-urls.csv
  default:
    cmds:
      - task -l
    silent: true
