---
# https://taskfile.dev

version: '3'

tasks:
  backup:
    desc: Backup a LastPass vault
    cmds:
      - lpass export > {{ .FILENAME }}
    vars:
      FILENAME: backup.csv
  clean:
    desc: ⚠️ Clean the dir of csv files including backup.csv!
    cmds:
      - rm *.csv
  deps:
    desc: Install dependencies
    cmds:
      - brew install $(cat formulas)
  lint:
    desc: Lint the project
    cmds:
      - shellcheck -x ./check-urls.sh
  pinentry:
    desc: Set pinentry
    cmds:
      - ./check-urls.sh {{ .FILENAME }}
    env:
      LPASS_DISABLE_PINENTRY: 1
    vars:
      FILENAME: dead-urls.csv
  urls:
    desc: Check for dead urls
    cmds:
      - ./check-urls.sh {{ .FILENAME }}
    vars:
      FILENAME: dead-urls.csv
  rm:
    desc: Remove LastPass items with dead urls
    cmds:
      - ./rm-dead-url-items.sh {{ .FILENAME }}
    vars:
      FILENAME: dead-urls.csv
  names:
    desc: Check for items to be renamed
    cmds:
      - ./check-names.sh {{ .FILENAME }}
    vars:
      FILENAME: rename.csv
  rename:
    desc: Rename items in the LastPass vault
    cmds:
      - ./rename.sh {{ .FILENAME }}
    vars:
      FILENAME: rename.csv
  default:
    cmds:
      - task -l
    silent: true
