#!/bin/bash

# Check if the command exists
function command_exists(){                                                                                                                                                                                                                   
  command -v "${1}" &> /dev/null                                                                                                                                                                                                             
}   

# Check is variable is null                                                                                                                                                                                                                  
function is_null {                                                                                                                                                                                                                           
  [ -z "$1" ]                                                                                                                                                                                                                                
}   

function test_domain(){                                                                                                                                                                                                                      
  curl -sSf "${1}" >/dev/null 2>&1                                                                                                                                                                                                           
  return $?                                                                                                                                                                                                                                  
}

function get_domain(){
  f=$(echo "${1}" | sed -e 's/[^/]*\/\/\([^@]*@\)\?\([^:/]*\).*/\2/')
  f="${f#www.}"
  f="${f#www1.}"
  f="${f#www2.}"
  echo "${f}"
}

# https://github.com/lastpass/lastpass-cli/issues/560#issuecomment-724266729
function get_data(){
  lpass show --expand-multi --basic-regexp '.*' --json
}

# printf usage_error if something isn't right.
function usage_error() {
  show_usage "${1}"
  printf "\nTry %s -h for more options.\n" "${1}" >&2
  exit 1
}

function show_usage(){
  printf "Usage: %s [OPTIONS] FILENAME\n" "${1}"
}

function show_version(){
  printf "%s version %s\n" "${1}" "${2}"; exit 0
}

function script_desc(){
  printf "%s\n\n" "${1}"
}

# Show the help
function show_help(){
  show_usage "${1}"
  script_desc "${2}"
  printf "Mandatory arguments:\n"
  printf "  FILENAME            The filename to export the dead urls to\n\n"
  printf "Options:\n"
  printf "  -h, --help          Print this Help.\n"
  printf "  -v, --version       Print script version and exit.\n"
  exit 0
}

function check_apps(){
  ! command_exists lpass  && printf "lpass is not installed\n" && exit 1
  ! command_exists jq     && printf "jp is not installed\n" && exit 1
  ! command_exists curl   && printf "curl is not installed\n" && exit 1
}
