#!/bin/bash

# Check if the command exists
function command_exists(){                                                                                                                                                                                                                   
  command -v "${1}" &> /dev/null                                                                                                                                                                                                             
}   

# Check is variable is null                                                                                                                                                                                                                  
function is_null {                                                                                                                                                                                                                           
  [ -z "$1" ]                                                                                                                                                                                                                                
}   

function test_domain(){                                                                                                                                                                                                                      
  curl -sSf "${1}" >/dev/null 2>&1                                                                                                                                                                                                           
  return $?                                                                                                                                                                                                                                  
}

function get_domain(){
  f=$(echo "${1}" | sed -e 's/[^/]*\/\/\([^@]*@\)\?\([^:/]*\).*/\2/')
  f="${f#www.}"
  f="${f#www1.}"
  f="${f#www2.}"
  echo "${f}"
}

# https://github.com/lastpass/lastpass-cli/issues/560#issuecomment-724266729
function get_data(){
  lpass show --expand-multi --basic-regexp '.*' --json
}
